In [2]:
import numpy as np
import pandas as pd

In [4]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2024-12-12 15:06:52--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: ‘laptops.csv’

laptops.csv         100%[===================>] 291,58K   989KB/s    in 0,3s    

2024-12-12 15:06:53 (989 KB/s) - ‘laptops.csv’ saved [298573/298573]



In [5]:
pd.__version__

'2.2.3'

In [52]:
df = pd.read_csv('laptops.csv')

Q2. Records count

How many records are in the dataset?

In [8]:
df.shape

(2160, 12)

Q3. Laptop brands

How many laptop brands are presented in the dataset?

In [20]:
len(df['Brand'].unique())

27

Q4. Missing values

How many columns in the dataset have missing values?

In [21]:
df.isna().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

Q5. Maximum final price

What's the maximum final price of Dell notebooks in the dataset?

In [26]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [36]:
df[df['Brand'] == 'Dell']['Final Price'].max()

np.float64(3936.0)

Q6. Median value of Screen

In [58]:
median = df['Screen'].median()
median

np.float64(15.6)

In [56]:

mode = df['Screen'].mode()[0]
df['Screen'] = df['Screen'].fillna(mode)

# df['Screen'].isna().sum()
median2 = df['Screen'].median()
median2

np.float64(15.6)

Q7. Sum of weights

In [66]:
df_7 = df[df["Brand"] == 'Innjoo']

In [69]:
df_7 = df_7[['RAM','Storage','Screen']]

In [71]:
arr = df_7.to_numpy()
arr

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [109]:
arr_T = arr.T
XTX = np.dot(arr_T,arr)
XTX


array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [110]:
det_XTX = np.linalg.det(XTX)
if det_XTX != 0:
    XTX_inv = np.linalg.inv(XTX)
    print("Inverse of A:\n", XTX_inv)

Inverse of A:
 [[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [111]:
y = [1100, 1300, 800, 900, 1000, 1100]

In [118]:
w = np.dot(XTX_inv,arr_T)

w = np.dot(w,y)
sum(w)



np.float64(91.2998806299555)